import { BrainCircuit, Code2, Figma, Globe, Layers, Rocket, Server, ShoppingCart } from 'lucide-react'

export const services = [
  { id: 'websites', icon: Globe, title: 'Business websites',
    summary: 'A considered digital presence that makes your business easy to understand and easy to contact.',
    description: 'We bring content, design, and development together to build websites that reflect your company and guide visitors to the right next step.',
    includes: ['Content structure and page design', 'Responsive development and CMS integration', 'Search foundations and performance optimization'],
    tech: ['Next.js', 'React', 'Content management'] },
  { id: 'web-apps', icon: Code2, title: 'Web applications',
    summary: 'Custom portals, dashboards, and internal tools built around the way your business works.',
    description: 'We turn complex workflows into straightforward software, connecting your users, data, and existing systems in one coherent experience.',
    includes: ['Customer portals and operational dashboards', 'User accounts, permissions, and reporting', 'Integrations with your existing business tools'],
    tech: ['React', 'TypeScript', 'Node.js'] },
  { id: 'saas', icon: Layers, title: 'SaaS platforms',
    summary: 'Subscription products with a clear user experience and a foundation for continued growth.',
    description: 'From onboarding to billing and administration, we design and develop the connected features your product needs to operate as a business.',
    includes: ['Multi-tenant architecture and team management', 'Subscriptions, billing, and account settings', 'Product analytics and administration tools'],
    tech: ['Next.js', 'PostgreSQL', 'Stripe'] },
  { id: 'ecommerce', icon: ShoppingCart, title: 'E-commerce experiences',
    summary: 'Thoughtful storefronts that connect product discovery, purchasing, and business operations.',
    description: 'We build shopping experiences around your catalog and customers, with clear product information and a considered path through checkout.',
    includes: ['Custom storefronts and collection navigation', 'Product options, cart, and payment integration', 'Inventory and order management connections'],
    tech: ['Shopify', 'Next.js', 'Stripe'] },
  { id: 'ai', icon: BrainCircuit, title: 'AI & workflow automation',
    summary: 'Practical tools that help your team find information and reduce repetitive work.',
    description: 'We start with a specific business task, then build and evaluate the right approach using your data, existing tools, and review requirements.',
    includes: ['Knowledge assistants and document processing', 'Connected workflows and human review steps', 'Evaluation, monitoring, and usage controls'],
    tech: ['Python', 'AI integrations', 'Vector search'] },
  { id: 'api', icon: Server, title: 'APIs & backend systems',
    summary: 'The integrations and infrastructure that keep your software connected and maintainable.',
    description: 'We design the services behind your product with clear data models, documented interfaces, and an approach to deployment your team can maintain.',
    includes: ['REST and GraphQL APIs', 'Data migrations and third-party integrations', 'Cloud deployment, logging, and monitoring'],
    tech: ['Node.js', 'PostgreSQL', 'Cloud infrastructure'] },
  { id: 'ui', icon: Figma, title: 'Product design & interfaces',
    summary: 'Clear navigation, purposeful interaction, and a consistent visual language across your product.',
    description: 'We translate requirements into user journeys, interface designs, and reusable components. We can also develop from your existing design files.',
    includes: ['User journeys, wireframes, and interface design', 'Design systems and component libraries', 'Responsive implementation and accessibility reviews'],
    tech: ['Figma', 'React', 'Design systems'] },
  { id: 'mvp', icon: Rocket, title: 'MVP & product development',
    summary: 'A focused first release that gives your idea a practical path to real user feedback.',
    description: 'We help you define the essential product, make the technical decisions, and plan a first release with room to learn and develop further.',
    includes: ['Product discovery and scope definition', 'Prototypes and core feature development', 'Launch planning and iterative improvements'],
    tech: ['Prototyping', 'Full-stack development', 'Product iteration'] },
]

export const serviceFaqs = [
  { question: 'How do you scope a project?', answer: 'We start with your goals, users, existing systems, and constraints. From there, we outline the deliverables, dependencies, milestones, and estimate for your review.' },
  { question: 'Can you work with our existing product or team?', answer: 'Yes. We can review an existing codebase, implement your designs, develop specific features, or collaborate with your internal team on a larger release.' },
  { question: 'How are timelines and costs agreed?', answer: 'Both depend on scope and complexity. We agree on a delivery plan and commercial terms before development begins, and discuss the impact of changes before adding them to the work.' },
  { question: 'How do we stay involved during development?', answer: 'We agree on meeting times that work for both teams, share progress through regular demonstrations, and keep decisions and feedback documented.' },
  { question: 'What happens after launch?', answer: 'We plan the handover, documentation, and support requirements with you. Ongoing maintenance and feature development can be arranged around your product roadmap.' },
]
